
server:
  port: 51230

# 企微配置
wechat:
  config:
    corp-id: wwd9033b37c6e802bf
    corp-secret: rWGZwA8OMYRSbHQB9IBkA8zEytuvDnxRNpbu11RmdPg

spring:
  application:
    name: wechat-token
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.65:43306/block_chain?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mysqlroot
    druid:
      max-active: 8
      min-idle: 1
  redis:
    host: 192.168.31.65
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: -1
  elasticsearch:
    rest:
      uris: http://192.168.31.65:9200
mybatis:
  mapper-locations: mapper/**/*.xml
